services:
  - type: web
    name: kotlinchat-server
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: kotlinchat-db
          property: connectionString

databases:
  - name: kotlinchat-db
    plan: free
